#lang planet neil/sicp

(define (smallest-divisor n)
  (define (square x)
    (* x x))
  (define (find-divisor base)
    (cond ((> (square base) n) n)
          ((= (remainder n base) 0) base)
          (else (find-divisor (inc base)))))
  (find-divisor 2))

(define (prime? x)
  (= (smallest-divisor x) x))
(define (square x)
  (* x x))

(define (expmod base exp m)
  (cond ((= exp 0) 1)
         ((even? exp) (remainder (square (expmod base (/ exp 2) m)) m))
         (else (remainder (* base (expmod base (- exp 1) m)) m))))

(define (fast-prime? x)
  (define (have-try a x)
    (= (expmod a x x) a))
  (define (fermat-test x n)
    (cond ((= n 0) true)
          ((have-try (+ (random (- x 1)) 1) x) (fermat-test x (dec n)))
          (else false)))
  (fermat-test x 3))

(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))

(define (start-prime-test n start-time)
  (if (fast-prime? n) (report-prime (- (runtime) start-time))))

(define (report-prime cost-time)
  (display " *** ")
  (display cost-time))

(define (find-prime-beyond n)
  (define (find-prime-beyond-times-timed x t)
    (timed-prime-test x)
    (find-prime-beyond-times (inc x) (dec t)))
  (define (find-prime-beyond-times x t)
    (cond ((> t 0)
           (if (fast-prime? x)
               (find-prime-beyond-times-timed x t)
               (find-prime-beyond-times (inc x) t)))))
  (find-prime-beyond-times n 3))


(find-prime-beyond 100)
(newline)
(find-prime-beyond 1000)
(newline)
(find-prime-beyond 10000)
(newline)
(find-prime-beyond 100000)
(newline)
(find-prime-beyond 1000000)
(newline)
(find-prime-beyond 10000000)
;(fast-prime? 19999)